# Generated by Django 3.2.6 on 2021-08-28 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('completed', models.IntegerField(choices=[(0, 'NOT_COMPLETED'), (1, 'COMPLETED_ADMIN_EDIT'), (10, 'FULLY_COMPLETED'), (11, 'FULLY_COMPLETED_ADMIN_EDIT')], verbose_name='status_completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
