# Generated by Django 3.2.6 on 2021-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210828_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotext',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
