# Generated by Django 3.2.6 on 2021-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todotext_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotext',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todotext',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
